# This code is generated by PyUIbuilder: https://github.com/PaulleDemon/PyUIBuilder

import tkinter as tk
import tkintermapview
from tktimepicker import AnalogPicker, AnalogThemes, constants

janelamain = tk.Tk()
janelamain.config(bg="#E4E2E2")
janelamain.title("Busca")

frame = tk.Frame(master=janelamain)
frame.config(bg="#5b7cd7")
frame.grid(row=1, column=1)

sair = tk.Button(master=frame, text="Sair")
sair.config(bg="#ffffff", fg="#000", bd=1, relief="GROOVE", font=("Courier", 14, ))
sair.place(x=584.1191654994625, y=325.0120191923702, width=88, height=23)

option_options = ["option 1","option 2","option 3","option 4","option 5","option 6","option 7","option 8","option 9","option 10","option 11","option 12"]
option_var = tk.StringVar(value="option 2")
option = tk.OptionMenu(frame, option_var, *option_options)
option.config(bg="#fff", fg="#000", bd=1, relief="SUNKEN", font=("Courier", 12, ))
option.place(x=321.1790934463666, y=112.79367786006571, width=120, height=30)

roleta = tk.Spinbox(master=frame)
roleta.config(from_=0, to=100, increment=1, value=0, bg="#fff", fg="#000", font=("Courier", 12, ))
roleta.place(x=611.9553042090602, y=222.44902921226665, width=48, height=NaN)

scale_var = tk.DoubleVar(value=0)
scale = tk.Scale(master=frame, variable=scale_var)
scale.config(bg="#fff", fg="#000", from_=0, to=100, resolution=1, orientation=vertical)
scale.place(x=567.191605463509, y=61.299713728282356, width=120, height=22)

top_level = tk.Toplevel(master=janelamain)
top_level.config(bg="#E4E2E2")
top_level.title("Top level")

frame1 = tk.Frame(master=top_level)
frame1.config(bg="#e78e8e")
frame1.grid(row=1, column=1)

botaosair = tk.Button(master=frame1, text="Sair")
botaosair.config(bg="#ffffff", fg="#000", bd=1, relief="FLAT", font=("Courier", 14, ), cursor="hand2")
botaosair.place(x=472.9144758234026, y=195.62084457810488, width=65, height=22)

map_ = tkintermapview.TkinterMapView(master=frame1)
map_.grid(row=1, column=1)

time = AnalogPicker(parent=frame1, type=constants.HOURS12)
time_theme = AnalogThemes(time)
time_theme.setDracula()
time.place(x=400.707639134825, y=29.369000057241518, width=147, height=102)


janelamain.mainloop()